### ISSUE TITLE
Error:The system cannot find the file specified

### ISSUE THREAD

**Issue by farooqaziz20** [Mmalherbe/MassiveCNC#7]
get the "CreateProcess returned 2 (The system cannot find the file specified)" error

**Comment by Mmalherbe** [comment]
Hi,

In the hierarchy under controllers select the cncapi_controller and set the EdingCNCPath correctly ( To the cnc.ini in the installed location of EdingCNC4.03 

For example : C:\Users\M\Desktop\CNC4.03\cnc.ini
